[package]
name = "the_guy_that_who_asked"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.11.6", default-features = false, features = ["client", "gateway", "model", "rustls_backend", "cache"] }
tokio = { version = "1.32.0", features = ["full"] }
